
build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs"
  contactDetails:
    name: "Rana-product owner"
    email: "rana@learningbytes.com"
  onCallSupport:
    9986667891