
build:
  version: "3.1"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "satya-Developer"
    email: "satya@learningbytes.com"
  onCallSupport:
    9986647589