
build:
  version: "3.2"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "satya-Developer"
    email: "satya@learningbytes.com"
  onCallSupport:
    9986647589