spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/skopparapu/LearningBytes.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
       # native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//satya//Documents//config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
encrypt:
  key: "UWDAqMJNo1lu2NW48DxJZEBJfi5fOGBV"

server:
  port: 8071
logging:
  pattern:
    level: "%5p[${spring.application.name}, %X{trace_id}, %X{span_id}]"